// Stats: GitHub
export const FETCH_STATS_GITHUB_STARTED = 'FETCH_STATS_GITHUB_STARTED';
export const FETCH_STATS_GITHUB_SUCCEEDED = 'FETCH_STATS_GITHUB_SUCCEEDED';
export const FETCH_STATS_GITHUB_FAILED = 'FETCH_STATS_GITHUB_FAILED';
